language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,libflac-dev], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,libflac-dev],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,libflac-dev],sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head,libflac-dev],  sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - case "$CABALVER" in
    "1.18") cabal configure --enable-tests --enable-library-coverage -v2 -f dev ;;
    *)      cabal configure --enable-tests --enable-coverage -v2 -f dev ;;
   esac
 - cabal build
 - cabal test --show-details=always
 - cabal sdist
 - cabal haddock | grep "100%" | wc -l | grep "3"

after_script:
 - cabal install hpc-coveralls
 - export PATH=~/.cabal/bin:$PATH
 - hpc-coveralls --coverage-mode=StrictlyFullLines
                 --exclude-dir=pure-tests
                 --exclude-dir=httpbin-tests
                 pure-tests httpbin-tests

notifications:
  email: false
